# Stage 1: Build the React application
FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the built application with Nginx
FROM nginx:1.24-alpine as server

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the build output from the builder stage to the Nginx static file directory
COPY --from=builder /app/dist /usr/share/nginx/html



# Expose the default Nginx port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
